version: '3.8'

services:
  elasticsearch:
    image: m.daocloud.io/docker.io/elasticsearch:7.17.28
    container_name: dragin-simplified-elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - xpack.security.enabled=false
      - network.host=0.0.0.0
      - http.port=9200
      - transport.tcp.port=9300
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - dragin-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  dragin:
    image: crpi-lxfoqbwevmx9mc1q.cn-chengdu.personal.cr.aliyuncs.com/tari_tech/dragin-simplified:latest
    container_name: dragin-simplified-app
    depends_on:
      elasticsearch:
        condition: service_healthy
    volumes:
      - ${HF_HOME:-.cache/huggingface}:/root/.cache/huggingface
      - ${SOURCE_PATH:-.}:/app
    networks:
      - dragin-network
    environment:
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT=9200
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - HF_ENDPOINT=https://hf-mirror.com
      - CUDA_VISIBLE_DEVICES=3
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    stdin_open: true
    tty: true
    command: /bin/bash

volumes:
  elasticsearch_data:
  huggingface_cache:

networks:
  dragin-network:
    driver: bridge